[programs.localnet]
harmonia = "5urSProYo2jCcyEid4Ytv3wE8fQbQRPV3UUPj7Hmac1u"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/localnet.json"

[scripts]
test = "mocha --require ts-node/register ./tests/*.ts --timeout 300000"
