[programs.localnet]
harmonia = "HARm9wjX7iJ1eqQCckXdd1imRFXE6PsVChVdV4PbfLc"

[clusters.devnet]
harmonia = "HARm9wjX7iJ1eqQCckXdd1imRFXE6PsVChVdV4PbfLc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/localnet.json"

[scripts]
test = "mocha --require ts-node/register ./tests/*.ts --timeout 300000"
